/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewGUI;

/**
 *
 * @author jesus.olier
 */
public class VistaRequerimientos_Principal extends javax.swing.JFrame {

    /**
     * Creates new form VistaRequerimientos_Principal
     */
    public VistaRequerimientos_Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequerimineto3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRequerimineto1 = new javax.swing.JButton();
        btnRequerimineto2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jesus Olier");
        setBackground(javax.swing.UIManager.getDefaults().getColor("tab_focus_fill_lower"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 204, 204));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequerimineto3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRequerimineto3.setText("Requerimiento 3");
        btnRequerimineto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimineto3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimineto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 160, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Definicion Reto5 - Ciclo 2 Mision TIC 2022");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 400, -1));

        btnRequerimineto1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRequerimineto1.setText("Requerimiento 1");
        btnRequerimineto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimineto1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimineto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 70));

        btnRequerimineto2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRequerimineto2.setText("Requerimiento 2");
        btnRequerimineto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequerimineto2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRequerimineto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequerimineto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimineto1ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento1 VistaFrame = new VistaRequerimiento1();
        VistaFrame.setVisible(true);
    }//GEN-LAST:event_btnRequerimineto1ActionPerformed

    private void btnRequerimineto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimineto2ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento2 VistaFrame = new VistaRequerimiento2();
        VistaFrame.setVisible(true);
    }//GEN-LAST:event_btnRequerimineto2ActionPerformed

    private void btnRequerimineto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequerimineto3ActionPerformed
        // TODO add your handling code here:
        VistaRequerimiento3 VistaFrame = new VistaRequerimiento3();
        VistaFrame.setVisible(true);
    }//GEN-LAST:event_btnRequerimineto3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientos_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientos_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequerimineto1;
    private javax.swing.JButton btnRequerimineto2;
    private javax.swing.JButton btnRequerimineto3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
